### PR TITLE
#43 Misprints in README.md

### PR DESCRIPTION
**Pull request by paulodamaso**
I've found some typos, take a look.

### CODE REVIEW

**Comment by skapral** [comment]
@paulodamaso Thank you.

Could you please mention these typos in issue #43 and mention the issue's number in the commit message, like it is done for the rest?

**Comment by skapral** [comment]
@paulodamaso please apply my remark, or otherwise I'd be left no options but decline the PR and do everything for myself. Sorry.

**Comment by paulodamaso** [comment]
@skapral Done, sorry for the delay!

**Comment by skapral** [comment]
@paulodamaso thanks. What about commit message? You may just amend and force-repush it to the same branch, it won't take much time from you.

**Comment by paulodamaso** [comment]
@skapral I changed commit message from GitHub site but looks like it did not worked, will change it later then.

**Comment by paulodamaso** [comment]
@skapral Take a look now please.

**Pull request merged**
